version: '3.8'

services:
  ems-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mongo
    networks:
      - ems-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ems
    networks:
      - ems-network

volumes:
  mongo-data:

networks:
  ems-network:
    driver: bridge
